# Broker MQTT del plano de administración (VLAN 3, 10.30.30.20)
# - Recibe la telemetría de las zonas (llega a través del enrutador inter-VLAN)
# - La ESP32 esclava de LEDs se conecta desde la WiFi al puerto publicado 1883 del PC
listener 1883 0.0.0.0
allow_anonymous true
persistence false
log_dest stdout
log_type error
log_type warning
log_type notice
connection_messages true
